#!/usr/bin/env python3
"""
Generate District Consolidation collection organized by NY county.

Parses markdown files from OCR table extraction and groups them by county,
handling continuation pages where county headers may be missing.
"""

import re
from collections import defaultdict
from pathlib import Path
from typing import Dict, List, Tuple

# Configuration
MARKDOWN_DIR = Path('output/ocr/tables/markdown')
OUTPUT_PATH = Path('output/collections/district-consolidation-by-county.md')
GITHUB_REPO = "zmuhls/csa"
BRANCH = "main"


def extract_page_number(filename: str) -> int:
    """Extract page number from filename like District-Consolidation-Data_100-116_page_50.md"""
    match = re.search(r'_page_(\d+)\.md$', filename)
    if match:
        return int(match.group(1))
    return 0


def parse_markdown_file(filepath: Path) -> Dict:
    """Parse a markdown file to extract county, table type, and metadata."""
    content = filepath.read_text(encoding='utf-8')
    lines = content.split('\n')

    result = {
        'filepath': filepath,
        'filename': filepath.name,
        'page_number': extract_page_number(filepath.name),
        'county': None,
        'table_type': None,
        'is_placeholder': False,
    }

    # Extract county from first line (# County Name County)
    if lines and lines[0].startswith('# '):
        header = lines[0][2:].strip()
        if header.endswith(' County'):
            county_name = header[:-7].strip()  # Remove " County" suffix
            if county_name.lower() == 'county':
                result['is_placeholder'] = True
                result['county'] = None
            else:
                result['county'] = county_name

    # Extract table type
    for line in lines:
        if line.startswith('**Table Type:**'):
            result['table_type'] = line.replace('**Table Type:**', '').strip()
            break

    return result


def collect_all_files() -> List[Dict]:
    """Collect and parse all markdown files, sorted by page number."""
    files = []

    for filepath in MARKDOWN_DIR.glob('District-Consolidation-Data_*.md'):
        parsed = parse_markdown_file(filepath)
        files.append(parsed)

    # Sort by page number
    files.sort(key=lambda x: x['page_number'])

    return files


def assign_counties(files: List[Dict]) -> List[Dict]:
    """Assign counties to placeholder pages based on continuation logic."""
    current_county = None

    for f in files:
        if f['county']:
            current_county = f['county']
        elif f['is_placeholder'] and current_county:
            # This is a continuation of the previous county
            f['county'] = current_county
        elif f['is_placeholder']:
            # No previous county to inherit from
            f['county'] = 'Unknown'

    return files


def group_by_county(files: List[Dict]) -> Dict[str, List[Dict]]:
    """Group files by county name."""
    grouped = defaultdict(list)

    for f in files:
        county = f['county'] or 'Unknown'
        grouped[county].append(f)

    # Sort each group by page number
    for county in grouped:
        grouped[county].sort(key=lambda x: x['page_number'])

    return grouped


def format_github_url(filepath: Path) -> str:
    """Generate GitHub blob URL for markdown file."""
    relative = filepath.relative_to(Path('.'))
    return f"https://github.com/{GITHUB_REPO}/blob/{BRANCH}/{relative}"


def format_thumb_url(page_number: int) -> str:
    """Generate GitHub raw URL for thumbnail."""
    return f"https://raw.githubusercontent.com/{GITHUB_REPO}/{BRANCH}/output/ocr/tables/thumbs/District-Consolidation-Data_100-116_page_{page_number}.jpg"


def generate_markdown(grouped: Dict[str, List[Dict]]) -> str:
    """Generate the collection markdown file."""
    lines = [
        "<!-- This file is auto-generated by scripts/generate_county_collection.py -->",
        "",
        "# District Consolidation Data by County",
        "",
        "This collection organizes the District Consolidation tables from NYS Archives by county. Each entry links to the extracted markdown table and includes a thumbnail of the source document.",
        "",
        "---",
        "",
        "## Table of Contents",
        "",
    ]

    # Generate TOC
    sorted_counties = sorted(grouped.keys(), key=lambda x: (x == 'Unknown', x))
    for county in sorted_counties:
        anchor = county.lower().replace(' ', '-')
        count = len(grouped[county])
        lines.append(f"- [{county} County](#-{anchor}-county) ({count} pages)")

    lines.append("")
    lines.append("---")
    lines.append("")

    # Generate county sections
    for county in sorted_counties:
        files = grouped[county]
        lines.append(f"## {county} County")
        lines.append("")

        for f in files:
            page = f['page_number']
            table_type = f['table_type'] or 'Unknown'
            md_url = format_github_url(f['filepath'])
            thumb_url = format_thumb_url(page)

            lines.append(f"- [Page {page} - {table_type}]({md_url})")
            lines.append(f"  [![Page {page}]({thumb_url})]({md_url})")
            lines.append("")

        lines.append("---")
        lines.append("")

    # Footer
    lines.extend([
        "## Notes",
        "",
        "- **Source**: District-Consolidation-Data_100-116.pdf from NYS Archives",
        "- **Extraction**: Tables extracted via multimodal AI (Qwen VL Plus)",
        "- **Regenerate**: Run `python scripts/generate_county_collection.py` to refresh",
        ""
    ])

    return "\n".join(lines)


def main():
    print("=" * 70)
    print("District Consolidation Collection Generator (by County)")
    print("=" * 70)
    print()

    # Collect files
    print("Collecting markdown files...")
    files = collect_all_files()
    print(f"  Found {len(files)} files")

    # Assign counties to placeholders
    print("Assigning counties to continuation pages...")
    files = assign_counties(files)

    placeholder_count = sum(1 for f in files if f['is_placeholder'])
    print(f"  Resolved {placeholder_count} placeholder pages")

    # Group by county
    print("Grouping by county...")
    grouped = group_by_county(files)
    print(f"  Found {len(grouped)} counties")

    # List counties
    for county in sorted(grouped.keys()):
        print(f"    - {county}: {len(grouped[county])} pages")

    # Generate markdown
    print()
    print("Generating collection markdown...")
    markdown = generate_markdown(grouped)

    # Write output
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(markdown, encoding='utf-8')
    print(f"  Written to: {OUTPUT_PATH}")

    print()
    print("=" * 70)
    print("Done!")
    print("=" * 70)


if __name__ == '__main__':
    main()
